### ISSUE TITLE
fix multi-part AOI input processing for non-Oracle vector layers

### ISSUE THREAD

**Issue by rustyjux** [bcgov/qgis-reports-plugin#19]
Only one AOI is processed, after a long hang during processing:
![image](https://user-images.githubusercontent.com/38586679/171906843-a8f6a385-dd2f-4a80-b5c6-e5428e6db538.png)

Should follow pattern used for BCGW to add features to `feature_layer_lst` and then `mergevectorlayer`

**Comment by wburt** [comment]
Fixed in dev and merged to main
